Add controllers
AzamatKarabashev/java-shareit pull request #1
Opened 2024-02-07 06:25 UTC by AzamatKarabashev

2024-02-07 20:19 UTC, avlin87 requested changes
Привет, Азамат,
Хорошая работа!
Всего 3 комментария.

2024-02-07 20:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/exception/BadRequestException.java
> +public class BadRequestException extends RuntimeException {
При создании своих исключений лучше избегать имен уже существующих исключений в Java библиотеке.
https://docs.oracle.com/javaee/7/api/javax/ws/rs/BadRequestException.html

Переименуй, пожалуйста, например в MyBadRequestException или CustomBadRequestException, или что-то другое.

2024-02-07 20:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException {
EntityNotFoundException так же существует в hibernate. 
В свою очередь hibernate часто используется для работы с базами данных.
Лучше переименовать.

2024-02-07 20:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryDaoImpl.java
> +    public Boolean isEmailAlreadyExist(String email) {
`Можно лучше`
Могу посоветовать использовать stream, чтобы получилось что-то такое:

```
public boolean isEmailAlreadyExist(String email) {
    if (email == null || email.isEmpty()) {
        return false;
    }
    return users.values().stream()
            .map(User::getEmail)
            .anyMatch(email::equals);
}
```

2024-02-07 20:33 UTC, AzamatKarabashev commented on src/main/java/ru/practicum/shareit/exception/BadRequestException.java
> +public class BadRequestException extends RuntimeException {
принял!

2024-02-07 20:33 UTC, AzamatKarabashev commented on src/main/java/ru/practicum/shareit/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException {
шикарно!

2024-02-07 20:34 UTC, AzamatKarabashev commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryDaoImpl.java
> +    public Boolean isEmailAlreadyExist(String email) {
гений! как же я соскучился по твоим комментариям, Лучший!

2024-02-08 02:55 UTC, avlin87 approved these changes
Работу принимаю.

2024-02-08 05:16 UTC, merged