/add-booking /первый коммит на PR
AzamatKarabashev/java-shareit pull request #2
Opened 2024-02-10 04:24 UTC by AzamatKarabashev

2024-02-11 03:38 UTC, avlin87 requested changes
Привет, Азамат,
Хорошая работа, оставил два комментария, смотри, пожалуйста, ниже.

2024-02-11 03:38 UTC, avlin87 commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
Мне кажется, что не стоить очищать все данные.
В реальной жизни мы рискуем удалить реальные данные.

2024-02-11 03:38 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static void bookingTimeValidation(BookingRequestDto requestDto) {
1. Валидации лучше проводить на уровне `Service`.
`Controller` выполняет роль "общения" с внешним миром.
`Service` валидации, логика, отправка запроса дальше на уровень хранения данных - Repository.

2. Static методы лучше избегать - они усложняют тестирование и обслуживание кода.

2024-02-12 07:42 UTC, AzamatKarabashev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static void bookingTimeValidation(BookingRequestDto requestDto) {
absolutely RIGHT!

2024-02-12 07:43 UTC, AzamatKarabashev commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
гениально! я даже не подумал, что удалять файлы смысла нет!

2024-02-13 01:36 UTC, avlin87 approved these changes
Работу принимаю.
Оставил один комментарий `можно лучше` на то, чтобы у метода убрать static.

2024-02-13 01:36 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +    private static void bookingTimeValidation(BookingRequestDto requestDto) {
Убери, пожалуйста, `static`

2024-02-13 07:34 UTC, merged